# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import defs_pb2 as defs__pb2


class FetchStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Capitalize = channel.unary_unary(
                '/rpc.Fetch/Capitalize',
                request_serializer=defs__pb2.Payload.SerializeToString,
                response_deserializer=defs__pb2.Payload.FromString,
                )


class FetchServicer(object):
    """Missing associated documentation comment in .proto file"""

    def Capitalize(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FetchServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Capitalize': grpc.unary_unary_rpc_method_handler(
                    servicer.Capitalize,
                    request_deserializer=defs__pb2.Payload.FromString,
                    response_serializer=defs__pb2.Payload.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rpc.Fetch', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Fetch(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def Capitalize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rpc.Fetch/Capitalize',
            defs__pb2.Payload.SerializeToString,
            defs__pb2.Payload.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
